# Generated by Django 5.0.6 on 2024-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2014-08-16'),
            preserve_default=False,
        ),
    ]
